version: '3'

services:
  db:
    build:
      context: ./db
    container_name: db
    image: db:prod
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wb_parsed_data

  cont1:
    build:
      context: ./cont1
    container_name: cont1
    image: cont1:prod
    depends_on:
      - db

  cont2:
    build:
      context: ./cont2
    container_name: cont2
    image: cont2
    ports:
      - "8080:8080"
    depends_on:
      - cont1